title: Conference Deadlines for CALAS
description: Countdowns to top conference deadlines for CALAS
author: CALAS

domain: ""
baseurl: "https://cityuhk-calas.github.io/conference-ddl"

twitter_hashtag: calas
github_username: D4rkCrypto
github_repo: calas-ddl

markdown: kramdown
ga_id:

include: ['_pages']
