title: Conference Deadlines for CALAS
description: Countdowns to top conference deadlines for CALAS
author: CALAS

domain: ""
baseurl: "https://cityuhk-calas.github.io/deadlines"

twitter_hashtag: ""
github_username: cityuhk-calas
github_repo: deadlines

markdown: kramdown
ga_id:

include: ['_pages']
